version: "3.7"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hYjx2f
      MYSQL_USER: user
      MYSQL_PASSWORD: fKjt43
      MYSQL_DATABASE: chat
    restart: always
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - mysql:db
      ports:
          - 8000:80
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
volumes:
  mysql-volume: